# -*- coding: utf-8 -*-
"""Vector search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0VcNlvtfYtG3taO9MR_FAkK_K54w4RG
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from sentence_transformers import SentenceTransformer, util
from sklearn.cluster import AgglomerativeClustering

# ──────────────────────────────────────────────
# 1. DATASET
# ──────────────────────────────────────────────
documents = [
    "How can I reset my account password?",
    "How can I reset my account password?",
    "I forgot my credentials and need to change my password.",
    "The stock market experienced a significant drop today.",
    "Major indices fell sharply as investors reacted to new economic data.",
    "I am having trouble logging in, can you help with a password reset?",
    "Wall Street closes lower amid concerns over rising inflation..."
]
labels = [f"D{i+1}" for i in range(len(documents))]

# ──────────────────────────────────────────────
# 2. VECTORIZARE (Batch Encoding)
# ──────────────────────────────────────────────
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(documents, normalize_embeddings=True)

# ──────────────────────────────────────────────
# 3. MATRICE DE SIMILARITATE COSINUS
# ──────────────────────────────────────────────
sim_matrix = util.cos_sim(embeddings, embeddings).numpy()

# ──────────────────────────────────────────────
# 4. DETECTARE PERECHI (Duplicate + Similare)
# ──────────────────────────────────────────────
DUPLICATE_THRESHOLD = 0.85
SIMILAR_THRESHOLD   = 0.60

duplicates, similar_pairs = [], []

for i in range(len(documents)):
    for j in range(i + 1, len(documents)):
        score = sim_matrix[i][j]
        if score >= DUPLICATE_THRESHOLD:
            duplicates.append((i, j, score))
        elif score >= SIMILAR_THRESHOLD:
            similar_pairs.append((i, j, score))

# ──────────────────────────────────────────────
# 5. CLUSTERING SEMANTIC (Aglomerativ)
# ──────────────────────────────────────────────
distance_matrix = 1 - sim_matrix
distance_matrix = np.clip(distance_matrix, 0, None)

clustering = AgglomerativeClustering(
    n_clusters=None,
    distance_threshold=1 - SIMILAR_THRESHOLD,
    metric='precomputed',
    linkage='average'
)
cluster_labels = clustering.fit_predict(distance_matrix)
unique_clusters = np.unique(cluster_labels)

# ──────────────────────────────────────────────
# 6. VIZUALIZARE — Dashboard
# ──────────────────────────────────────────────
plt.rcParams.update({
    'font.size': 13,
    'axes.titlesize': 14,
    'axes.labelsize': 13,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'legend.fontsize': 11,
})

fig = plt.figure(figsize=(22, 15))
fig.suptitle("Detectarea Similarității între Documente — Vector Search",
             fontsize=20, fontweight='bold', y=0.98)

cluster_colors = ['#e74c3c', '#3498db', '#2ecc71', '#f39c12', '#9b59b6']
doc_colors = [cluster_colors[c % len(cluster_colors)] for c in cluster_labels]

# ── 6a. Heatmap ──────────────────────────────
ax1 = fig.add_subplot(2, 2, 1)
annot_labels = np.array([[f"{sim_matrix[i][j]:.2f}" if i != j else "—"
                           for j in range(len(documents))]
                          for i in range(len(documents))])

sns.heatmap(sim_matrix, annot=annot_labels, fmt='', ax=ax1,
            cmap="RdYlGn", vmin=0, vmax=1,
            xticklabels=labels, yticklabels=labels,
            linewidths=0.8, linecolor='white', square=True,
            annot_kws={"size": 12},
            cbar_kws={'label': 'Scor Cosinus', 'shrink': 0.8})

for i, j, _ in duplicates:
    ax1.add_patch(mpatches.FancyBboxPatch(
        (j, i), 1, 1, fill=False, edgecolor='red', lw=2.5,
        boxstyle="square,pad=0"
    ))
    ax1.add_patch(mpatches.FancyBboxPatch(
        (i, j), 1, 1, fill=False, edgecolor='red', lw=2.5,
        boxstyle="square,pad=0"
    ))

ax1.set_title("Matricea de Similaritate Cosinus\n(roșu = duplicate detectate)",
              fontsize=14, fontweight='bold')
ax1.tick_params(axis='x', rotation=0)
ax1.tick_params(axis='y', rotation=0)

# ── 6b. Bar chart ────────────────────────────
ax2 = fig.add_subplot(2, 2, 2)
all_pairs = [(i, j, sim_matrix[i][j])
             for i in range(len(documents))
             for j in range(i + 1, len(documents))]
all_pairs.sort(key=lambda x: -x[2])
top_n = 8

pair_labels_plot = [f"{labels[i]}↔{labels[j]}" for i, j, _ in all_pairs[:top_n]]
pair_scores      = [s for _, _, s in all_pairs[:top_n]]
bar_colors = ['#e74c3c' if s >= DUPLICATE_THRESHOLD
              else '#3498db' if s >= SIMILAR_THRESHOLD
              else '#95a5a6'
              for s in pair_scores]

bars = ax2.barh(pair_labels_plot[::-1], pair_scores[::-1],
                color=bar_colors[::-1], edgecolor='white', height=0.6)
ax2.axvline(DUPLICATE_THRESHOLD, color='red',  linestyle='--', lw=1.5, alpha=0.7,
            label=f'Prag duplicat ({DUPLICATE_THRESHOLD})')
ax2.axvline(SIMILAR_THRESHOLD,   color='blue', linestyle='--', lw=1.5, alpha=0.7,
            label=f'Prag similar ({SIMILAR_THRESHOLD})')
ax2.set_xlabel("Scor Similaritate Cosinus")
ax2.set_title("Top Perechi după Scor", fontsize=14, fontweight='bold')
ax2.set_xlim(0, 1.05)
ax2.legend(fontsize=11, loc='lower right')
ax2.spines[['top', 'right']].set_visible(False)

for bar, score in zip(bars, pair_scores[::-1]):
    ax2.text(bar.get_width() + 0.01, bar.get_y() + bar.get_height() / 2,
             f'{score:.2%}', va='center', fontsize=11)

# ── 6c. Spatiu Vectorial 2D ──────────────────
ax3 = fig.add_subplot(2, 2, 3)
try:
    import umap
    reducer = umap.UMAP(n_components=2, random_state=42, n_neighbors=3, min_dist=0.3)
    coords = reducer.fit_transform(embeddings)
    method = "UMAP"
except ImportError:
    from sklearn.decomposition import PCA
    coords = PCA(n_components=2).fit_transform(embeddings)
    method = "PCA"

for idx, (x, y) in enumerate(coords):
    ax3.scatter(x, y, s=250, color=doc_colors[idx],
                edgecolors='white', linewidths=1.5, zorder=3)
    ax3.annotate(f" {labels[idx]}", (x, y), fontsize=12,
                 fontweight='bold', va='center')

for i, j, s in duplicates + similar_pairs:
    c  = 'red' if s >= DUPLICATE_THRESHOLD else 'steelblue'
    lw = 2.5   if s >= DUPLICATE_THRESHOLD else 1.2
    ax3.plot([coords[i][0], coords[j][0]],
             [coords[i][1], coords[j][1]],
             color=c, lw=lw, alpha=0.6, zorder=2)

legend_els = [
    mpatches.Patch(color=cluster_colors[i], label=f'Grup {i+1}')
    for i in range(len(unique_clusters))
]
ax3.legend(handles=legend_els, fontsize=11, loc='best')
ax3.set_title(f"Spațiu Vectorial 2D ({method})\n(linii = perechi detectate)",
              fontsize=14, fontweight='bold')
ax3.axis('off')

# ── 6d. Rezumat text ─────────────────────────
ax4 = fig.add_subplot(2, 2, 4)
ax4.axis('off')

summary_lines = [
    ("REZUMAT ANALIZĂ", 17, 'black', 'bold'),
    ("", 8, 'white', 'normal'),
    (f"  Total documente:     {len(documents)}", 13, '#2c3e50', 'normal'),
    (f"  Model utilizat:      all-MiniLM-L6-v2", 13, '#2c3e50', 'normal'),
    (f"  Prag duplicat:       {DUPLICATE_THRESHOLD}", 13, '#2c3e50', 'normal'),
    (f"  Prag similaritate:   {SIMILAR_THRESHOLD}", 13, '#2c3e50', 'normal'),
    ("", 8, 'white', 'normal'),
    (f"DUPLICATE DETECTATE ({len(duplicates)})", 14, '#e74c3c', 'bold'),
]
for i, j, s in sorted(duplicates, key=lambda x: -x[2]):
    summary_lines.append((f"  {labels[i]} ↔ {labels[j]}: {s:.2%}", 12, '#c0392b', 'normal'))

summary_lines.append(("", 8, 'white', 'normal'))
summary_lines.append((f"SIMILARE ({len(similar_pairs)})", 14, '#2980b9', 'bold'))
for i, j, s in sorted(similar_pairs, key=lambda x: -x[2]):
    summary_lines.append((f"  {labels[i]} ↔ {labels[j]}: {s:.2%}", 12, '#1a6ea8', 'normal'))

summary_lines.append(("", 8, 'white', 'normal'))
summary_lines.append((f"GRUPURI SEMANTICE ({len(unique_clusters)})", 14, '#27ae60', 'bold'))
for cl in unique_clusters:
    members = [labels[i] for i, c in enumerate(cluster_labels) if c == cl]
    summary_lines.append((f"  Grup {cl+1}: {', '.join(members)}", 12, '#1e8449', 'normal'))

y_pos = 0.97
for text, size, color, weight in summary_lines:
    ax4.text(0.05, y_pos, text, transform=ax4.transAxes,
             fontsize=size, color=color, fontweight=weight,
             verticalalignment='top', fontfamily='monospace')
    y_pos -= size * 0.016

ax4.set_facecolor('#f8f9fa')
ax4.set_title("Raport Detectare", fontsize=14, fontweight='bold')

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig("similarity_dashboard.png", dpi=150, bbox_inches='tight')
plt.show()